### PR TITLE
Save chosen theme in localStorage parameter

### PR DESCRIPTION
**Pull request by Adrion**
I add the possibility to save in localStorage the selected theme.
I had to tweak this in my project. 
Hope you'll accept to update it with your library ;)

### CODE REVIEW

**Comment by fdomig** [comment]
Hi Adrion, thanks for your addition. I am fine with your changes.

**Comment by Adrion** [comment]
Nice ;)

**Comment by Adrion** [comment]
I'll wait for the bower release

**Comment by fdomig** [comment]
Sorry, I missed that. It's released now.

**Comment by Adrion** [comment]
Thank !

**Comment by Adrion** [comment]
You can also update the live example for users ^^

**Pull request merged**
